### ISSUE TITLE
Editor not displaying in MS Edge

### ISSUE THREAD

**Issue by MontaguSteps** [Draggable/formeo#265]
I'm trying to get an absolute bare-essentials example of the Formeo editor working, but can't get it to display in MS Edge.  Below is the source of my minimal HTML page.  The editor displays and works in Firefox and Chrome, but in MS Edge I get a blank page and the console reports "Unspecified error" in formeo.min.js at (5,19275).  Is there a problem in Formeo or am I doing something wrong?

```
<!DOCTYPE html>
<head>
    <script src="https://draggable.github.io/formeo/assets/js/formeo.min.js" ></script>
    <link rel="stylesheet" href="https://draggable.github.io/formeo/assets/css/formeo.min.css" />
</head>
<body>
    <div id="editor"></div>
    <script>
        var f = new FormeoEditor({editorContainer: '#editor'});
    </script>
</body>
</html>
```

**Comment by MontaguSteps** [comment]
Further to this, the demo page [https://draggable.github.io/formeo/](https://draggable.github.io/formeo/) also fails to display the form builder when viewed in MS Edge, or IE.

**Comment by tsawler** [comment]
I have no problem with MS Edge...

**Comment by MontaguSteps** [comment]
Interesting... Windows ver?  I'm seeing this issue on Win 10 version 1909 (10.0.18383).  Tried twiddling smartscreen and popup blocker options in Edge, but no difference.  Couldn't see any other settings that looked like they might be relevant.
On the Formeo demo page I'm seeing different errors in the javascript console compared to with my test page as per the first post.  On the demo page I get:

> [object Error]: {description: "JSON.parse Error: Invalid character at position:1", message: "JSON.parse Error: Invalid character at position:1", number: -2146822633, stack: "SyntaxError: JSON.parse Error: Invalid character at position:1 at get.value (https://draggable.github.io/formeo/assets/js/demo.min.js:6:19342) at o.loadResources (https://draggable.github.io/formeo/assets/js/demo.min.js:24:125386) at t (https://draggable.github.io/formeo/assets/js/demo.min.js:24:111243) at Anonymous function (https://draggable.github.io/formeo/assets/js/demo.min.js:24:161235) at o (https://draggable.github.io/formeo/assets/js/demo.min.js:6:345) at Anonymous function (https://draggable.github.io/formeo/assets/js/demo.min.js:6:404) at Anonymous function (https://draggable.github.io/formeo/assets/js/demo.min.js:6:242) at Anonymous function (https://draggable.github.io/formeo/assets/js/demo.min.js:6:152) at Global code (https://draggable.github.io/formeo/assets/js/demo.min.js:6:1)"}
> 
> 0: JSON.parse Error: Invalid character at position:1
> demo.min.js (23,161260)
> 
> 0: Object doesn't support this action
> demo.min.js (23,69175)
